### ISSUE TITLE
Wrong sentiment ranges

### ISSUE THREAD

**Issue by george-kozlov** [skyttle/sentiment-evaluation#1]
Hi Viktor,

Nice to meet you virtually.
I would like to highlight the issue I noticed in your code related to Semantria service.
To be honest it's minor but it would be good if you can fix that.

In semantria_api.py (https://github.com/skyttle/sentiment-evaluation/blob/master/semantria_api.py) file you have extract_label method.
There you decide which label to return based on Semantria sentiment_score field.
If Semantria score is less than 0 you return '-', if greater, than '+'.

Meanwhile Semantria recommends other ranges for the neutral sentiment polarity so comparing of Semantria score with 0 isn't correct.
The correct ranges for document sentiment score are:
- Negative is lower than -0.05
- Neutral is between -0.05 and 0.22
- Positive is greater than 0.22

Additional information about Semantria sentiment score can be found here - http://support.semantria.com/customer/portal/articles/834168-about-semantria-s-sentiment-analysis

Can you please make necessary changes in your code?
Looking forward for your help.
## 

Regards,
George

**Comment by vpekar** [comment]
Hi George,

Thanks for letting me know. I've changed the thresholds as you requested. I am closing the issue.

Best regards,
Viktor

**Comment by george-kozlov** [comment]
Viktor,

Thanks for rapid response, I appreciate it!

## 

Cheers,
George
